### ISSUE TITLE
dim inactive sign column

### ISSUE THREAD

**Issue by sho-87** [rose-pine/neovim#123]
### Neovim version (nvim -v)

0.8.3

### Terminal

Windows Terminal

### Describe the bug

When using `dim_nc_background = true`, the sign column in inactive windows does not dim correctly, and still uses the active window bg colour:

![image](https://user-images.githubusercontent.com/5199715/219614531-e880a6b6-df55-48af-a1da-17bd079e634f.png)

Would it also make more sense to invert the bg colours? I would expect that when something is dimmed, it would get darker and not lighter

### Steps To Reproduce

1. Turn on sign column to the left of line numbers
2. turn on `dim_nc_background`

### Expected Behavior

1. Sign bg colour to be dimmed like the rest of the inactive window

**Comment by mvllow** [comment]
Thanks for pointing this bug out. I don't usually use this option and it definitely needed some love. #114 should greatly improve the experience when using `dim_nc_background`.

Inactive backgrounds are now actually dimmed instead of brightened and telescope.nvim should have a more consistent appearance.

Feel free to try it in the canary branch or wait for that to be merged into main soon :)

**Comment by sho-87** [comment]
thank you!
